# 4장 판다스 데이터 분석

In [1]:
import numpy as np
import pandas as pd

### 시리즈(Series)

In [2]:
# numpy에서는 인덱스를 [0], [1]로만 표현이 가능하지만
# pandas에서는 임의의 인덱스를 부여할 수 있다. (문자열도 가능)
# 인덱스는 주지 않아도 문제없다.
# [0], ["서울"] 모두 가능하다.
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s 

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
# [0], [1], [2], [3]으로 인덱싱된다.
x = np.array([9904312, 3448737, 2890451, 2466052])
x

array([9904312, 3448737, 2890451, 2466052])

In [4]:
# 인덱싱을 주지 않은경우(numpy와 차이 없음)
pd.Series(range(10, 14))

0    10
1    11
2    12
3    13
dtype: int64

In [5]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [6]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [7]:
# 이름은 데이터프레임으로 만들 때 한 colum의 제목이 될 수 있다.
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

### 시리즈 연산

In [8]:
# 인덱스에는 영향을 주지 않고 벡터화 연산을 할 수 있다.
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

### 시리즈 인덱싱

In [9]:
s[1], s['부산']

(3448737, 3448737)

In [10]:
# 배열 인덱싱으로 부분적인 값을 갖고오거나, 원하는 순서로 갖고 올 수 있다.
s[[0, 3, 1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [11]:
s[["서울", "대구", "부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [12]:
s[(250e4 < s) & (s < 500e4)] # 인구가 250만 초과, 500만 미만인 경우(e4는 0이 4개))

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [13]:
# 숫자로하면 [1], [2]에 해당하는 인덱싱이 나온다. ([3] 제외)
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [14]:
# 이름으로하면 마지막 인덱싱까지 포함해서 나온다.
s["부산":"대구"]  # 부산에서 대구까지 (대구도 포함)

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [15]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [16]:
s0.a

0

In [17]:
s0.b

1

### 시리즈와 딕셔너리 자료형

In [18]:
# 시리즈는 인덱스와 값으로 구성되어있어, 인덱스 = 키, 값 = 값으로 놓으면
# 딕셔너리자료형과 동일한 구성이다.
"서울" in s  # 인덱스 라벨 중에 서울이 있는가

True

In [19]:
"대전" in s  # 인덱스 라벨 중에 대전이 있는가

False

In [21]:
for k, v in s.items():
    print(f"{k} = {v}")

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [22]:
# 딕셔너리를 시리즈로 묶으면 키값이 인덱스, 값이 value로 바로 들어 갈 수 있다.
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [25]:
# 딕셔너리는 순서대로 나오지 않기때문에, 딕셔러니 생성 후 인덱스를 순서대로 주면
# 원하는 순서대로 출력된다.
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
                index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [24]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [27]:
# 인덱스가 같은 요소끼리 -를 하며, 실수로 변환된다.
# 한쪽에만 있는경우에는 NaN에러가 발생한다.(Not a Number)
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [28]:
# 그냥 자료형끼리 -를 하면, 인덱스가 일치하지 않아 엉터리 자료가된다.
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [29]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [30]:
# 값이 있는것만 출력
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [32]:
# 인구 증가율(%) 구하기
rs = (s - s2) / s * 100
rs = rs[rs.notnull()]
rs

부산    1.610619
서울    2.754659
인천    8.940335
dtype: float64

### 데이터의 갱신, 추가, 삭제

In [33]:
# 데이터 갱신
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.754659
인천    8.940335
dtype: float64

In [34]:
# 데이터 추가
rs["대구"] = 1.41
rs

부산    1.630000
서울    2.754659
인천    8.940335
대구    1.410000
dtype: float64

In [35]:
# 데이터 삭제
del rs["서울"]
rs

부산    1.630000
인천    8.940335
대구    1.410000
dtype: float64

In [37]:
# a = 현재주가, b = 전날주가
a = pd.Series([286500, 546000, 60000, 359500], index=["네이버", "오뚜기", "삼성전자", "다음"])
b = pd.Series([298000, 550000, 60200, 87300], index=["네이버", "오뚜기", "삼성전자", "LG전자"])

In [38]:
# 현재주가 - 전날주가
c = b-a
c

LG전자        NaN
네이버     11500.0
다음          NaN
삼성전자      200.0
오뚜기      4000.0
dtype: float64

In [39]:
c[c.notnull()]

네이버     11500.0
삼성전자      200.0
오뚜기      4000.0
dtype: float64

In [40]:
# 증감률(%)
d = (a - b) / a * 100
d = d[d.notnull()]
d

네이버    -4.013962
삼성전자   -0.333333
오뚜기    -0.732601
dtype: float64

In [44]:
# 여러 인덱스 주는법(멀티인덱스)
f = pd.Series([286500, 546000, 60000, 359500],
                index=[["포털", "포털", "기타", "전자"],                             ["네이버", "다음", "오뚜기", "삼성전자"]])
f

포털  네이버     286500
    다음      546000
기타  오뚜기      60000
전자  삼성전자    359500
dtype: int64

# 데이터프레임 클래스

In [63]:
# 데이터프레임 생성
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9853972, 3655437, 2466338, 2473990],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9853972  9853972         0.0283
부산  경상권  3448737  3393191  3655437  3655437         0.0163
인천  수도권  2890451  2632035  2466338  2466338         0.0982
대구  경상권  2466052  2431774  2473990  2473990         0.0141

In [49]:
# columns를 주지 않으면, dict의 key값이 columns명이 된다.
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2100-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
# columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
dx = pd.DataFrame(data, index=index)#, columns=columns)
dx

2015     2010     2005   지역  2100-2015 증가율
서울  9904312  9631482  9853972  수도권         0.0283
부산  3448737  3393191  3655437  경상권         0.0163
인천  2890451  2632035  2466338  수도권         0.0982
대구  2466052  2431774  2473990  경상권         0.0141

In [51]:
df.values

array([['수도권', 9904312, 9631482, 9853972, nan, nan],
       ['경상권', 3448737, 3393191, 3655437, nan, nan],
       ['수도권', 2890451, 2632035, 2466338, nan, nan],
       ['경상권', 2466052, 2431774, 2473990, nan, nan]], dtype=object)

In [52]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [53]:
dx.columns

Index(['2015', '2010', '2005', '지역', '2100-2015 증가율'], dtype='object')

In [54]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [85]:
# 데이터프레임에 name 주기
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9853972  9853972          -2.26
부산  경상권  3448737  3393191  3655437  3655437          -7.17
인천  수도권  2890451  2632035  2466338  2466338           6.72
대구  경상권  2466052  2431774  2473990  2473990          -1.71

In [68]:
# 연습문제
stock = {
    "현재주가": [86100, 60100, 546000, 24500, 358500],
    "전일주가": [87300, 60200, 550000, 21800, 371500],
    "동일업종 PER": [58.42, 18.14, 21.49, -3.60, 143.41],
    "시가총액순위": ["21위", "1위", "117위", "61위", "10위"],
    "액면가/1주": [5000, 100, 5000, 5000, 500]
}
columns = ["현재주가", "전일주가", "동일업종 PER", "시가총액순위", "액면가/1주"]
index = ["LG전자", "삼성전자", "오뚜기", "대한항공", "카카오"]
stockDf = pd.DataFrame(stock, index=index, columns=columns)
stockDf

현재주가    전일주가  동일업종 PER 시가총액순위  액면가/1주
LG전자   86100   87300     58.42    21위    5000
삼성전자   60100   60200     18.14     1위     100
오뚜기   546000  550000     21.49   117위    5000
대한항공   24500   21800     -3.60    61위    5000
카카오   358500  371500    143.41    10위     500

In [86]:
# .T 속성은 DataFrame 에서 index 와 column 을 바꾼 형태의 DataFrame
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9853972  3655437  2466338  2473990
2000           9853972  3655437  2466338  2473990
2005-2010 증가율    -2.26    -7.17     6.72    -1.71

### 열 인덱싱

In [87]:
# "2010-2015 증가율"이라는 이름의 열 갱신
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

KeyError: '2010-2015 증가율'

In [88]:
# "2005-2010 증가율"이라는 이름의 열 추가
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9853972  9853972          -2.26
부산  경상권  3448737  3393191  3655437  3655437          -7.17
인천  수도권  2890451  2632035  2466338  2466338           6.72
대구  경상권  2466052  2431774  2473990  2473990          -1.71

In [89]:
# "2010-2015 증가율"이라는 이름의 열 삭제
del df["2010-2015 증가율"]
df

KeyError: '2010-2015 증가율'

In [90]:
# 여러개의 열을 인덱싱하면 부분적인 데이터프레임이 반환된다.
# 밖의 []는 데이터 프레임을 유지하기위해서, 안쪽의 []는 리스트를 유지하기 위해서 (1개는 시리즈, 2개이상은 데이터프레임)
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [91]:
# 기본적으로 하나의 열만 인덱싱하면 시리즈가 반환된다.
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [92]:
# 2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
# 열 하나만을 갖는 데이터 프레임
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [73]:
type(df["지역"])

pandas.core.series.Series

In [74]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [75]:
# 열 인덱스가 있는 경우에는 열 인덱스 명을 적어주어야 에러가 나지 않는다.
df[0]

KeyError: 0

In [93]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [78]:
# 2차원 넘파이 배열이 들어간 데이터프레임
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [79]:
# 원래부터 문자열이 아닌, 정수형을 갖고있는경우에는 [정수]로 사용 가능하다.
df2[0]

0    0
1    4
2    8
Name: 0, dtype: int32

In [81]:
df2[[1, 2]]

1   2
0  1   2
1  5   6
2  9  10

### 행 인덱싱

In [94]:
# 행 인덱싱을 사용할 때에는 반드시 슬라이싱을 해주어야한다.
# 0번째 행 갖고오기
# 슬라이싱을 주지 않으면, 열로 판단하기때문에 슬라이싱을 사용한다.
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9853972  9853972          -2.26

In [95]:
df[1:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3655437  3655437          -7.17

In [96]:
df["서울":"부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9853972  9853972          -2.26
부산  경상권  3448737  3393191  3655437  3655437          -7.17

#### 개별 데이터 인덱싱 - 열, 행 순서로 적기

In [100]:
df['2015']['서울']

9904312

In [102]:
# 연습문제 4.1.3
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [104]:
# (1) 모든 학생의 수학 점수를 시리즈로 나타낸다.
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [105]:
# (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
df[["국어", "영어"]]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [108]:
# (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df["평균점수"] = ((df["국어"] + df["수학"] + df["영어"]) / 3).round(2)
df

국어  영어  수학   평균점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [127]:
# (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
del df["평균점수"]
df["영어"]["방자"] = 80
df["평균점수"] = ((df["국어"] + df["수학"] + df["영어"]) / 3).round(2)
df

국어  영어  수학   평균점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  60.00

In [128]:
# (5) 춘향의 점수를 데이터프레임으로 나타낸다.
df[:1].T

춘향
국어    80.00
영어    90.00
수학    90.00
평균점수  86.67

In [125]:
# (6) 향단의 점수를 시리즈로 나타낸다.
df.T["향단"]

국어      70.0
영어      60.0
수학      80.0
평균점수    70.0
Name: 향단, dtype: float64