In [48]:
import numpy as np

In [49]:
# 1. 길이가 10인 0-벡터 만들기
v = np.zeros((10))
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
# 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터 만들기
v2 = v
v2[4:5] = 1
v2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [51]:
# 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.
vc = np.arange(10, 50)
vc

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [52]:
# 4. 위(3번) 벡터의 순서를 바꾸세요.
vc[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [53]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.
th_th = np.arange(0, 9).reshape(3, 3)
th_th

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
# 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.
a = np.array([1,2,0,0,4,0])
b = a[a!=0]
b

array([1, 2, 4])

In [55]:
# 7. 3x3 단위 행렬(identity matrix)을 만드세요
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
# 8. 난수 원소를 가지는 3x3 행렬을 만드세요
na = np.random.rand(3, 3)
na

array([[0.93114343, 0.41543095, 0.02898166],
       [0.98202748, 0.33963768, 0.70668719],
       [0.36187707, 0.0351059 , 0.85505825]])

In [57]:
# 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.
na.max()

0.9820274845981977

In [58]:
# 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.
print('열 평균은', na.mean(axis=0), '입니다.')
print('행 평균은', na.mean(axis=1), '입니다.')

열 평균은 [0.75834933 0.26339151 0.53024237] 입니다.
행 평균은 [0.45851868 0.67611745 0.41734707] 입니다.
